apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: k8s.rules.container_cpu_limits
    namespace: integrations-kubernetes-container
spec:
    rules:
        - evaluationTime: 0.006635799
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-02-06T11:54:30.469986629Z"
          name: cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
          query: kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="cpu"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
          type: recording
        - evaluationTime: 0.003619876
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-02-06T11:54:30.476644184Z"
          name: namespace_cpu:kube_pod_container_resource_limits:sum
          query: sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
          type: recording
