apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kubernetes-system-controller-manager
    namespace: integrations-kubernetes
spec:
    rules:
        - alerts:
            - activeAt: "2025-02-06T11:14:08.72709636Z"
              annotations:
                description: KubeControllerManager has disappeared from Prometheus target discovery.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
                summary: Target disappeared from Prometheus target discovery.
              labels:
                alertname: KubeControllerManagerDown
                severity: critical
              state: firing
              value: "1e+00"
          annotations:
            description: KubeControllerManager has disappeared from Prometheus target discovery.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
            summary: Target disappeared from Prometheus target discovery.
          duration: 900
          evaluationTime: 0.002343248
          health: ok
          keepFiringFor: 0
          labels:
            severity: critical
          lastError: ""
          lastEvaluation: "2025-02-06T11:55:08.729187557Z"
          name: KubeControllerManagerDown
          query: absent(up{job="integrations/kubernetes/kube-controller-manager"} == 1)
          state: firing
          type: alerting
