apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertContactPoint
metadata:
    name: duplo-slack
spec:
    name: duplo-slack
    settings:
      url: https://hooks.slack.com/services/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
    disableResolveMessage: false
    type: slack
    uid: duplo-slack