apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
  name: critical-priority-rules
spec:
  folder: Integration-LinuxNode
  interval: 60
  rules:
    - condition: C
      data:
        - datasourceUid: duplo-metrics
          model:
            datasource:
              type: prometheus
              uid: duplo-metrics
            editorMode: code
            expr: |
              100 -
              (
                avg by (instance) (
                  node_memory_MemAvailable_bytes{job=~"integrations/(node_exporter|unix)", cluster=~".*", job=~".+"}
                )
                /
                avg by (instance) (
                  node_memory_MemTotal_bytes{job=~"integrations/(node_exporter|unix)", cluster=~".*", job=~".+"}
                )
                * 100
              )
              * on (instance) group_left(label_tenantname)
                label_replace(
                  kube_node_labels{cluster=~".*", job="integrations/kubernetes/kube-state-metrics"},
                  "instance",
                  "$1",
                  "label_kubernetes_io_hostname",
                  "(.+)"
                )
            instant: true
            intervalMs: 1000
            maxDataPoints: 43200
            refId: A
          refId: A
          relativeTimeRange:
            from: 1800
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params: []
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - B
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: reduce
          refId: B
          relativeTimeRange:
            from: 1800
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 90
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
          refId: C
          relativeTimeRange:
            from: 1800
      execErrState: Error
      for: 0s
      id: 1
      noDataState: NoData
      orgID: 1
      ruleGroup: critical-priority-rules
      title: Critical Memory usage
      uid: fe1kjxgd3pibke
    - condition: C
      data:
        - datasourceUid: duplo-metrics
          model:
            datasource:
              type: prometheus
              uid: duplo-metrics
            editorMode: code
            expr: |
              (sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{job=~"integrations/(node_exporter|unix)", mode!="idle"}[2m]))) * 100)
              * on (instance) group_left(label_tenantname)
                label_replace(
                  kube_node_labels{cluster=~".*", job="integrations/kubernetes/kube-state-metrics"},
                  "instance",
                  "$1",
                  "label_kubernetes_io_hostname",
                  "(.+)"
                )
            instant: true
            intervalMs: 1000
            maxDataPoints: 43200
            refId: A
          refId: A
          relativeTimeRange:
            from: 600
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params: []
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - B
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: reduce
          refId: B
          relativeTimeRange:
            from: 600
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 90
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
          refId: C
          relativeTimeRange:
            from: 600
      execErrState: Error
      for: 5m
      id: 2
      noDataState: NoData
      orgID: 1
      ruleGroup: critical-priority-rules
      title: Critical CPU Usage
      uid: ae4iqfd32jocgc
  title: Node alerts with node labels
